# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20160113_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dunning_1_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment reminder 1 date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dunning_2_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment reminder 2 date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sequence_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Sequence number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
