# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 11:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20170228_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='credit_reason',
            field=models.TextField(blank=True, verbose_name='Reason for credit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Invoice'), (1, 'Payment reminder'), (2, 'Dunning 1'), (3, 'Dunning 2'), (4, 'Collection')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='timezone',
            field=models.CharField(default='UTC', max_length=128),
        ),
    ]
