# Generated by Django 2.2.13 on 2021-02-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_changing_on_delete_handlers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
