# Generated by Django 2.2.24 on 2021-09-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='product_identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
